import { Sponsor } from 'src/interfaces/sponsor';

export const MOCK_SPONSORS: Sponsor[] = [
  {
    id: 1,
    name: 'John Doe',
    job_title: 'Marketing Director',
    company_name: 'Tech Innovations',
    budget: 50000,
    industry: 'Technology',
    topics: ['Artificial Intelligence', 'Cloud Computing'],
    event_attendee_personas: ['C-suite executives', 'Tech professionals'],
    key_objectives_for_event_sponsorship: [
      'Brand awareness',
      'Networking with industry leaders',
    ],
  },
  {
    id: 2,
    name: 'Jane Smith',
    job_title: 'Head of Marketing',
    company_name: 'Green Energy Solutions',
    budget: 30000,
    industry: 'Renewable Energy',
    topics: ['Sustainability', 'Green Tech'],
    event_attendee_personas: [
      'Environmental advocates',
      'Corporate sustainability leaders',
    ],
    key_objectives_for_event_sponsorship: [
      'Promote sustainable solutions',
      'Attract eco-conscious partners',
    ],
  },
  {
    id: 3,
    name: 'Carlos Hernandez',
    job_title: 'Senior VP of Marketing',
    company_name: 'Smart Home Inc.',
    budget: 45000,
    industry: 'Consumer Electronics',
    topics: ['Smart Homes', 'IoT'],
    event_attendee_personas: [
      'Tech enthusiasts',
      'Home automation professionals',
    ],
    key_objectives_for_event_sponsorship: [
      'Increase product visibility',
      'Engage with potential distributors',
    ],
  },
  {
    id: 4,
    name: 'Sara Wilson',
    job_title: 'Marketing Manager',
    company_name: 'Digital Health Solutions',
    budget: 25000,
    industry: 'Healthcare',
    topics: ['Digital Health', 'Telemedicine'],
    event_attendee_personas: [
      'Healthcare providers',
      'Tech developers in healthcare',
    ],
    key_objectives_for_event_sponsorship: [
      'Raise awareness for digital health innovations',
      'Build partnerships with healthcare professionals',
    ],
  },
  {
    id: 5,
    name: 'Michael Brown',
    job_title: 'Chief Marketing Officer',
    company_name: 'FinTech Partners',
    budget: 60000,
    industry: 'Financial Technology',
    topics: ['Blockchain', 'Cryptocurrency'],
    event_attendee_personas: ['Investors', 'Tech founders'],
    key_objectives_for_event_sponsorship: [
      'Lead generation',
      'Position as industry leader',
    ],
  },
  {
    id: 6,
    name: 'Emily Johnson',
    job_title: 'Marketing Specialist',
    company_name: 'Biotech Research Corp.',
    budget: 40000,
    industry: 'Biotechnology',
    topics: ['Genetic Research', 'Biotech Innovation'],
    event_attendee_personas: ['Biotech professionals', 'Researchers'],
    key_objectives_for_event_sponsorship: [
      'Showcase research advancements',
      'Connect with other biotech companies',
    ],
  },
  {
    id: 7,
    name: 'David Lee',
    job_title: 'VP of Marketing',
    company_name: 'Clean Water Inc.',
    budget: 35000,
    industry: 'Water Treatment',
    topics: ['Water Purification', 'Sustainability'],
    event_attendee_personas: [
      'Environmental engineers',
      'Government policy makers',
    ],
    key_objectives_for_event_sponsorship: [
      'Build brand recognition',
      'Educate attendees on clean water solutions',
    ],
  },
  {
    id: 8,
    name: 'Anna Nguyen',
    job_title: 'Head of Strategy',
    company_name: 'Auto Innovators',
    budget: 70000,
    industry: 'Automotive',
    topics: ['Electric Vehicles', 'Autonomous Cars'],
    event_attendee_personas: [
      'Automotive manufacturers',
      'Tech startups in transportation',
    ],
    key_objectives_for_event_sponsorship: [
      'Position as a leader in EV',
      'Explore potential collaborations',
    ],
  },
  {
    id: 9,
    name: 'Jack Taylor',
    job_title: 'CEO',
    company_name: 'Innovative Design Studio',
    budget: 15000,
    industry: 'Design',
    topics: ['User Experience', 'Product Design'],
    event_attendee_personas: ['Product designers', 'Creative directors'],
    key_objectives_for_event_sponsorship: [
      'Networking with potential clients',
      'Demonstrate design expertise',
    ],
  },
  {
    id: 10,
    name: 'Grace Walker',
    job_title: 'Director of Marketing',
    company_name: 'AgriTech Solutions',
    budget: 20000,
    industry: 'Agriculture',
    topics: ['Agricultural Technology', 'Precision Farming'],
    event_attendee_personas: ['Farmers', 'Agricultural innovators'],
    key_objectives_for_event_sponsorship: [
      'Promote new tech tools for farming',
      'Engage with agricultural stakeholders',
    ],
  },
  {
    id: 11,
    name: 'Ethan Davis',
    job_title: 'Marketing Lead',
    company_name: 'CyberSafe',
    budget: 55000,
    industry: 'Cybersecurity',
    topics: ['Data Protection', 'Cyber Threats'],
    event_attendee_personas: ['IT professionals', 'Security analysts'],
    key_objectives_for_event_sponsorship: [
      'Generate leads',
      'Showcase advanced security solutions',
    ],
  },
  {
    id: 12,
    name: 'Olivia Martinez',
    job_title: 'Marketing Strategist',
    company_name: 'Creative Cloud Media',
    budget: 30000,
    industry: 'Media & Entertainment',
    topics: ['Content Creation', 'Digital Media'],
    event_attendee_personas: ['Content creators', 'Media planners'],
    key_objectives_for_event_sponsorship: [
      'Brand visibility',
      'Engage with content creators',
    ],
  },
  {
    id: 13,
    name: 'Lucas Harris',
    job_title: 'Chief Innovation Officer',
    company_name: 'NanoTech Industries',
    budget: 50000,
    industry: 'Nanotechnology',
    topics: ['Nano Engineering', 'Material Science'],
    event_attendee_personas: ['Scientists', 'Engineers in advanced materials'],
    key_objectives_for_event_sponsorship: [
      'Promote cutting-edge technologies',
      'Connect with researchers',
    ],
  },
  {
    id: 14,
    name: 'Sophia Green',
    job_title: 'Marketing Manager',
    company_name: 'Luxury Automobiles',
    budget: 80000,
    industry: 'Automotive',
    topics: ['Luxury Cars', 'Performance Vehicles'],
    event_attendee_personas: [
      'High-net-worth individuals',
      'Luxury car enthusiasts',
    ],
    key_objectives_for_event_sponsorship: [
      'Brand positioning',
      'Connect with affluent consumers',
    ],
  },
  {
    id: 15,
    name: 'Ben White',
    job_title: 'Senior Marketing Director',
    company_name: 'SpaceTech Enterprises',
    budget: 60000,
    industry: 'Aerospace',
    topics: ['Space Exploration', 'Satellite Technology'],
    event_attendee_personas: [
      'Aerospace engineers',
      'Government space agencies',
    ],
    key_objectives_for_event_sponsorship: [
      'Position as an industry leader',
      'Build relationships with aerospace professionals',
    ],
  },
  {
    id: 16,
    name: 'Mia Scott',
    job_title: 'Head of Digital Marketing',
    company_name: 'Cloud Data Services',
    budget: 40000,
    industry: 'Cloud Computing',
    topics: ['Cloud Storage', 'Data Management'],
    event_attendee_personas: ['IT professionals', 'Tech innovators'],
    key_objectives_for_event_sponsorship: [
      'Promote cloud solutions',
      'Engage with potential clients',
    ],
  },
  {
    id: 17,
    name: 'James King',
    job_title: 'Marketing Director',
    company_name: 'EcoTech Enterprises',
    budget: 25000,
    industry: 'Environmental Technology',
    topics: ['Clean Energy', 'Environmental Solutions'],
    event_attendee_personas: [
      'Environmental engineers',
      'Green technology investors',
    ],
    key_objectives_for_event_sponsorship: [
      'Increase brand awareness',
      'Network with environmental advocates',
    ],
  },
  {
    id: 18,
    name: 'Chloe Adams',
    job_title: 'VP of Marketing',
    company_name: 'Retail Innovations',
    budget: 70000,
    industry: 'Retail',
    topics: ['E-commerce', 'Retail Trends'],
    event_attendee_personas: ['Retailers', 'Tech vendors in retail'],
    key_objectives_for_event_sponsorship: [
      'Showcase products',
      'Build partnerships with retailers',
    ],
  },
  {
    id: 19,
    name: 'Ryan Johnson',
    job_title: 'Chief Marketing Officer',
    company_name: 'HealthTech Innovators',
    budget: 50000,
    industry: 'Health Technology',
    topics: ['Health Monitoring', 'Wearables'],
    event_attendee_personas: [
      'Healthcare professionals',
      'Tech developers in healthcare',
    ],
    key_objectives_for_event_sponsorship: [
      'Generate awareness for wearable devices',
      'Meet healthcare stakeholders',
    ],
  },
  {
    id: 20,
    name: 'Lily Clark',
    job_title: 'Marketing Executive',
    company_name: 'Global Shipping',
    budget: 35000,
    industry: 'Logistics',
    topics: ['Supply Chain', 'Logistics Solutions'],
    event_attendee_personas: [
      'Supply chain managers',
      'Logistics professionals',
    ],
    key_objectives_for_event_sponsorship: [
      'Networking with logistics experts',
      'Increase global brand recognition',
    ],
  },
];
